name: HerokuDeploymentDemo
channels:
  - conda-forge
  - defaults
​
dependencies:
  - python=3.6
  - click
  - dnspython
  - Flask
  - Flask-SQLAlchemy
  - itsdangerous
  - Jinja2
  - MarkupSafe
  - psycopg2
  - pymongo
  - SQLAlchemy
  - Werkzeug
  - wincertstore
  - pip
  - pip:
    - gunicorn 
    
 entrypoint: gunicorn -b :$PORT main:app --timeout 90